name = "stm32_draw_demo"
description = "Draw on STM32"
version = "0.1.0"
licenses = "BSD-3-Clause"

authors = ["AdaCore, Olivier Henley, Kien Nguyen"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]
website="https://github.com/GNAT-Academic-Program/stm32_draw_demo"
tags = ["embedded", "stm32"]

executables = ["stm32_draw_demo"]

[[depends-on]]
stm32_gui = "0.1.0"

[[depends-on]]
#stm32f429disco = "0.1.0"
stm32f746disco = "0.1.0"

[[pins]]
gnat_arm_elf = { version='12.2.1' }